# Name of the workflow
name: Deploy to Render

# Controls when the action will run

on:

# Triggers the workflow on push events for the main branch

push:
branches:
\- main

# A workflow run is made up of one or more jobs

jobs:

# This workflow contains a single job called "deploy"

deploy:
\# The type of runner that the job will run on
runs-on: ubuntu-latest

name: Trigger Render Deploy
run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

