# Name of the workflow
name: Deploy to Render

# Controls when the action will run.

on:

# Triggers the workflow on push events but only for the main branch

push:
branches:
\- main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

# This workflow contains a single job called "deploy"

deploy:
\# The type of runner that the job will run on
runs-on: ubuntu-latest